// invitesRepo.js — manage team invites for the current tenant.
// RLS: manager/owner can read+write invites for their tenant. accept_invite is a
// SECURITY DEFINER RPC so anyone signed in can redeem a token.

import { supabase } from './supabaseClient.js';

function ctx() {
  return window.__RESTOPS_CTX__;
}

// List pending (unaccepted, unexpired) invites for the current tenant.
export async function listInvites({ includeAccepted = false } = {}) {
  const c = ctx();
  let q = supabase
    .from('invites')
    .select('id, email, role, token, expires_at, accepted_at, created_at, invited_by')
    .eq('tenant_id', c.tenantId)
    .order('created_at', { ascending: false });
  if (!includeAccepted) q = q.is('accepted_at', null);
  const { data, error } = await q;
  if (error) throw error;
  return (data || []).map(r => ({
    ...r,
    expired: new Date(r.expires_at) < new Date(),
    link: buildInviteLink(r.token),
  }));
}

// Create an invite. Token is auto-generated by DB default.
export async function createInvite({ email, role = 'staff' }) {
  const c = ctx();
  const cleanEmail = String(email || '').trim().toLowerCase();
  if (!cleanEmail || !cleanEmail.includes('@')) {
    throw new Error('Enter a valid email address');
  }
  if (!['owner', 'manager', 'staff'].includes(role)) {
    throw new Error('Invalid role');
  }

  const { data, error } = await supabase
    .from('invites')
    .insert({
      tenant_id: c.tenantId,
      email: cleanEmail,
      role,
      invited_by: c.user.id,
    })
    .select('id, email, role, token, expires_at, accepted_at, created_at')
    .single();

  if (error) throw error;
  return { ...data, link: buildInviteLink(data.token) };
}

// Revoke (delete) a pending invite.
export async function revokeInvite(inviteId) {
  const { error } = await supabase
    .from('invites')
    .delete()
    .eq('id', inviteId);
  if (error) throw error;
}

// Public peek at an invite — used on the accept page before the user signs in.
export async function previewInvite(token) {
  const { data, error } = await supabase.rpc('invite_preview', { _token: token });
  if (error) throw error;
  if (!data || !data.length) return null;
  return data[0];
}

// Redeem an invite — inserts the membership (via SECURITY DEFINER RPC) and marks invite accepted.
// Returns the tenant_id the user now belongs to.
export async function acceptInvite(token) {
  const { data, error } = await supabase.rpc('accept_invite', { _token: token });
  if (error) throw error;
  return data;
}

export function buildInviteLink(token) {
  const origin = window.location.origin;
  return `${origin}/invite.html?token=${encodeURIComponent(token)}`;
}
