// Phase 2 features: Inspection Prep, Recipe Costing, CRM, Scheduler, Briefing, Role switcher

// -----------------------------------------------------------------------------
// FL DBPR INSPECTION DATA — sourced from FL DBPR Food Code violation categories
// Severity: high = High Priority, intermediate = Intermediate, basic = Basic
// -----------------------------------------------------------------------------
export const DBPR_CHECKLIST = [
  // Foodborne Illness Risk Factors (Group)
  { group: "Food Sources & Handling", code: "01A", sev: "high",
    task: "Food received only from approved sources; receipts/invoices on file",
    detail: "All meat, cheese, produce from licensed distributors. No home-prepared food on premises." },
  { group: "Food Sources & Handling", code: "01B", sev: "high",
    task: "All food safe, unadulterated, wholesome condition — no dented cans, no spoiled items",
    detail: "Inspect incoming deliveries. Dented/damaged cans must be removed from inventory." },
  { group: "Food Sources & Handling", code: "02C", sev: "high",
    task: "Date-marking on all ready-to-eat TCS foods (cooked sauce, sliced meats, prepped veg)",
    detail: "7-day discard rule from prep/open date. Label with date opened and discard date." },
  { group: "Food Sources & Handling", code: "08A", sev: "high",
    task: "Raw animal foods stored below/separated from RTE foods",
    detail: "Raw chicken on bottom shelf, raw beef above, RTE items on top. Never above ready-to-eat." },
  { group: "Food Sources & Handling", code: "08B", sev: "intermediate",
    task: "Food protected during prep, storage, display — all containers covered",
    detail: "Lids or plastic wrap on prep bins, toppings, sauces." },

  // Time/Temperature Control
  { group: "Time & Temperature", code: "03A", sev: "high",
    task: "Cold-holding ≤ 41°F (walk-in, reach-in, prep line, topping rail)",
    detail: "Verify with calibrated thermometer at start of shift and every 4 hours." },
  { group: "Time & Temperature", code: "03B", sev: "high",
    task: "Hot-holding ≥ 135°F (wings warmer, hot wells, hot sauce)",
    detail: "Check hot-holding at peak and every 2 hours." },
  { group: "Time & Temperature", code: "03C", sev: "high",
    task: "Cooking temperatures correct (chicken 165°F, beef 155°F, pizza oven ≥ 500°F)",
    detail: "Stem thermometer probed into thickest part of food. Log temps for chicken wings." },
  { group: "Time & Temperature", code: "03D", sev: "high",
    task: "Cooling procedures documented (135°F → 70°F within 2hr; 70°F → 41°F within 4hr)",
    detail: "Hot pizza sauce, cooked meats must follow 2-stage cooling. Shallow pans only." },
  { group: "Time & Temperature", code: "03E", sev: "high",
    task: "Reheating to 165°F within 2 hours before hot-holding",
    detail: "Any previously cooked TCS food must reach 165°F throughout before going to hot-hold." },
  { group: "Time & Temperature", code: "03F", sev: "high",
    task: "Time as a Public Health Control — written procedure + 4-hour discard",
    detail: "If using TPHC for toppings on pizza line, label with start + discard time (4 hrs)." },
  { group: "Time & Temperature", code: "05", sev: "intermediate",
    task: "Calibrated stem thermometers (0–220°F) available and accurate",
    detail: "Ice water test monthly. Replace or recalibrate if off by >2°F." },

  // Employee Hygiene
  { group: "Employee Hygiene", code: "09", sev: "high",
    task: "No bare-hand contact with ready-to-eat food (gloves, tongs, deli paper)",
    detail: "Making pizzas, slicing, portioning wings — always use a barrier. Repeat-offender item." },
  { group: "Employee Hygiene", code: "11", sev: "high",
    task: "Employee health policy posted; no ill employees working with food",
    detail: "Big 6 symptoms (vomiting, diarrhea, jaundice, sore throat w/ fever, lesion, Norovirus/Salmonella/Shigella/E.coli/HepA) — send home." },
  { group: "Employee Hygiene", code: "12A", sev: "high",
    task: "Hands washed properly — dedicated handwash sink with hot water, soap, towels",
    detail: "20-second wash. Handwash sink NOT used for prep or dishes." },
  { group: "Employee Hygiene", code: "12B", sev: "intermediate",
    task: "No eating, drinking, smoking, or tasting in prep areas",
    detail: "Employee drinks must have lid + straw, stored below/separated from food." },
  { group: "Employee Hygiene", code: "13", sev: "intermediate",
    task: "Clean clothes, hair restraints, no painted/artificial nails, no jewelry (wedding band OK)",
    detail: "Aprons changed when soiled. Hair nets/hats on all prep staff." },
  { group: "Employee Hygiene", code: "31A", sev: "intermediate",
    task: "Handwash sinks accessible, unobstructed, not used for other purposes",
    detail: "Commonly cited — staff using handwash sinks for filling pitchers. Post signage." },
  { group: "Employee Hygiene", code: "31B", sev: "intermediate",
    task: "Handwash supplies stocked: soap, paper towels, handwash sign",
    detail: "Check every shift open and close." },

  // Cleaning & Sanitation
  { group: "Cleaning & Sanitation", code: "14", sev: "high",
    task: "Food-contact surfaces in good repair (cutting boards not deeply scored)",
    detail: "Replace pitted boards, damaged gaskets, rusted shelving." },
  { group: "Cleaning & Sanitation", code: "16", sev: "high",
    task: "Dishmachine sanitizer/temp working + test strips/thermometer available",
    detail: "Chlorine 50-100 ppm OR quat 200-400 ppm OR hot-water final rinse ≥ 160°F utensil surface." },
  { group: "Cleaning & Sanitation", code: "22", sev: "high",
    task: "Food-contact surfaces clean and sanitized (prep tables, slicers, pizza peels)",
    detail: "Every 4 hours during use + after each raw protein change-over." },
  { group: "Cleaning & Sanitation", code: "23", sev: "basic",
    task: "Non-food-contact surfaces clean (shelf exteriors, equipment legs, walls near prep)",
    detail: "Schedule deep cleans weekly. Grease buildup is a repeat-citation." },
  { group: "Cleaning & Sanitation", code: "24", sev: "intermediate",
    task: "Clean utensils/equipment stored to drain and air-dry",
    detail: "Never stack wet. Invert containers." },
  { group: "Cleaning & Sanitation", code: "21", sev: "basic",
    task: "Wiping cloths stored in sanitizer solution between uses",
    detail: "Chlorine 50-100 ppm. Test every 4 hours with test strips." },

  // Facility & Pest Control
  { group: "Facility & Pest Control", code: "35A", sev: "high",
    task: "No presence of pests (roaches, rodents, flies, ants) — active pest control contract",
    detail: "Pest control log on file. #1 closure reason in FL. Monthly professional service minimum." },
  { group: "Facility & Pest Control", code: "35B", sev: "intermediate",
    task: "Outer openings protected — screens intact, dock doors sealed, gaps filled",
    detail: "Gap under back door = mouse highway. Install door sweeps." },
  { group: "Facility & Pest Control", code: "36", sev: "basic",
    task: "Floors, walls, ceilings clean and in good repair; coving intact",
    detail: "No damaged tiles, no peeling paint near food. Floor-wall junction coved." },
  { group: "Facility & Pest Control", code: "33", sev: "basic",
    task: "Dumpster area clean, lid closed, drain plug in place",
    detail: "Grease barrel separate from trash. Absorbent material around area." },
  { group: "Facility & Pest Control", code: "38", sev: "basic",
    task: "Lighting adequate and bulbs shielded/shatterproof in food areas",
    detail: "50 foot-candles at prep surfaces, 20 at handwash, 10 in storage." },

  // Plumbing & Water
  { group: "Plumbing & Water", code: "27", sev: "high",
    task: "Hot (≥100°F) and cold water available under pressure at all sinks",
    detail: "Check handwash sinks especially — insufficient hot water is common." },
  { group: "Plumbing & Water", code: "28", sev: "high",
    task: "Sewage/wastewater disposed properly — no backups or cross-connections",
    detail: "Mop sink, floor drains clear and draining." },
  { group: "Plumbing & Water", code: "29", sev: "high",
    task: "Backflow prevention on all threaded faucets (mop sink, hose bibb)",
    detail: "Vacuum breakers/atmospheric backflow preventers required." },
  { group: "Plumbing & Water", code: "32", sev: "intermediate",
    task: "Restrooms clean, supplied, with self-closing doors",
    detail: "Soap, toilet paper, handwash signage, covered trash receptacles." },

  // Chemicals & Licensing
  { group: "Chemicals & Licensing", code: "41", sev: "high",
    task: "Chemicals stored separately from food, labeled, and approved for use",
    detail: "Degreaser next to pizza boxes = violation. Original labels must remain." },
  { group: "Chemicals & Licensing", code: "50", sev: "high",
    task: "Current DBPR license, properly displayed in public view",
    detail: "Near front door or at counter, clearly visible." },
  { group: "Chemicals & Licensing", code: "53A", sev: "intermediate",
    task: "Certified Food Manager on duty during operating hours (ServSafe or equivalent)",
    detail: "At least one ServSafe-Manager certified staff on site during all ops hours." },
  { group: "Chemicals & Licensing", code: "53B", sev: "basic",
    task: "Food-handler training for all employees within 30 days of hire",
    detail: "Keep certificates on file. Renewed every 3 years in FL." },
];

// Top 10 commonly-cited FL DBPR violations (2024–2025)
export const TOP_VIOLATIONS = [
  { code: "35A", title: "Pests (roaches, rodents, flies)", desc: "#1 cause of emergency closures in Central Florida — live or dead pests observed" },
  { code: "22",  title: "Food-contact surfaces not clean/sanitized", desc: "Slicers, prep tables, pizza peels with residue" },
  { code: "08A", title: "Raw proteins stored over RTE food", desc: "Raw chicken above cooked pasta, eggs above ready items" },
  { code: "03A", title: "Cold-holding above 41°F", desc: "Reach-in coolers, prep-line rails drifting warm" },
  { code: "12A", title: "Improper handwashing", desc: "Not washing hands between tasks, handwash sink used for other purposes" },
  { code: "02C", title: "No date-marking on RTE TCS food", desc: "Open cheese, cooked sauce, sliced deli meats missing prep/discard date" },
  { code: "14",  title: "Food-contact surfaces in disrepair", desc: "Deeply scored cutting boards, rusted shelving, damaged gaskets" },
  { code: "16",  title: "Dishmachine sanitizer failure", desc: "Chlorine < 50 ppm or hot water rinse not reaching 160°F" },
  { code: "09",  title: "Bare-hand contact with RTE food", desc: "Making sandwiches or topping pizzas without gloves/tongs" },
  { code: "31A", title: "Handwash sink blocked/used for other purposes", desc: "Sink obstructed by buckets, used for filling pitchers" },
];

export const MOCK_INSPECTION_QUESTIONS = [
  { code: "03A", q: "Inspector probes walk-in cooler at 9am. What's the temperature reading?" },
  { code: "08A", q: "Inspector opens reach-in. Raw chicken is on top shelf above cooked sauce. Pass or fail?" },
  { code: "12A", q: "Staff switches from raw chicken to making a pizza without washing hands. What happens?" },
  { code: "02C", q: "Open container of mozzarella in reach-in — no date mark. Inspector's call?" },
  { code: "35A", q: "Inspector spots two live roaches behind dish machine. What's the next step?" },
  { code: "22",  q: "Pizza peel being reused for raw dough and then raw chicken with no sanitization. Violation level?" },
  { code: "16",  q: "Dishmachine final rinse reads 148°F on thermometer. What happens?" },
  { code: "50",  q: "Inspector asks to see the DBPR license. It's in the back office. Is this OK?" },
  { code: "41",  q: "Spray bottle of degreaser stored on shelf above pizza boxes. Pass or fail?" },
  { code: "31A", q: "Handwash sink in prep area has a bucket of wiping cloths in it. What's cited?" },
];

export const MOCK_ANSWERS = {
  "03A": { pass: "Reading is 38°F — within 41°F limit. PASS.", fail: "Reading is 44°F — out of safe range. HIGH-PRIORITY VIOLATION." },
  "08A": { pass: "Actually cooked sauce was on top, raw chicken on bottom. PASS.", fail: "Raw over RTE. HIGH-PRIORITY — immediate correction required." },
  "12A": { pass: "Staff washed hands between tasks. PASS.", fail: "HIGH-PRIORITY violation 12A. Inspector may require retraining and could lead to reinspection." },
  "02C": { pass: "Container had date mark behind lid. PASS.", fail: "HIGH-PRIORITY 02C — stop sale issued on that product." },
  "35A": { pass: "Pest control log shows monthly service; one-time incident documented. PASS with note.", fail: "HIGH-PRIORITY 35A — possible emergency closure until follow-up inspection." },
  "22":  { pass: "Peel was swapped and sanitized between uses. PASS.", fail: "HIGH-PRIORITY 22 cross-contamination." },
  "16":  { pass: "Dishmachine uses chemical sanitizer instead — chlorine tested at 75ppm. PASS.", fail: "HIGH-PRIORITY 16 — dishes must be re-washed. Repair required before reopening dishmachine." },
  "50":  { pass: "License is in display frame at counter. PASS.", fail: "BASIC 50 — must be publicly displayed. Easy fix on-site." },
  "41":  { pass: "Chemicals stored in separate locked cabinet. PASS.", fail: "HIGH-PRIORITY 41 — chemicals cannot be stored above/near food or food packaging." },
  "31A": { pass: "Handwash sink clear, only soap/towels at station. PASS.", fail: "INTERMEDIATE 31A — handwash sink must be solely for handwashing." },
};

// -----------------------------------------------------------------------------
// RECIPES — costed to match the menu
// -----------------------------------------------------------------------------
export const SAMPLE_RECIPES = [
  { id: "r1", name: "Large Cheese Pizza", menuPrice: 16.99, yield: 1, ingredients: [
    { item: "00 Flour",            qty: 0.55, unit: "lb",  cost: 0.68 },
    { item: "Mozzarella (block)",  qty: 0.42, unit: "lb",  cost: 3.95 },
    { item: "San Marzano tomato",  qty: 0.08, unit: "#10", cost: 8.20 },
    { item: "Olive oil (gal)",     qty: 0.01, unit: "gal", cost: 32.00 },
    { item: "Yeast/salt/sugar",    qty: 1,    unit: "ea",  cost: 0.12 },
    { item: "Pizza box 16\"",      qty: 1/50, unit: "case",cost: 48.00 },
  ]},
  { id: "r2", name: "Large Pepperoni", menuPrice: 18.99, yield: 1, ingredients: [
    { item: "00 Flour",            qty: 0.55, unit: "lb",  cost: 0.68 },
    { item: "Mozzarella (block)",  qty: 0.42, unit: "lb",  cost: 3.95 },
    { item: "San Marzano tomato",  qty: 0.08, unit: "#10", cost: 8.20 },
    { item: "Pepperoni",           qty: 0.18, unit: "lb",  cost: 6.40 },
    { item: "Olive oil (gal)",     qty: 0.01, unit: "gal", cost: 32.00 },
    { item: "Pizza box 16\"",      qty: 1/50, unit: "case",cost: 48.00 },
  ]},
  { id: "r3", name: "Meat Lovers", menuPrice: 22.99, yield: 1, ingredients: [
    { item: "00 Flour",            qty: 0.55, unit: "lb",  cost: 0.68 },
    { item: "Mozzarella (block)",  qty: 0.45, unit: "lb",  cost: 3.95 },
    { item: "San Marzano tomato",  qty: 0.08, unit: "#10", cost: 8.20 },
    { item: "Pepperoni",           qty: 0.12, unit: "lb",  cost: 6.40 },
    { item: "Italian sausage",     qty: 0.18, unit: "lb",  cost: 5.10 },
    { item: "Bacon crumbles",      qty: 0.08, unit: "lb",  cost: 7.20 },
    { item: "Pizza box 16\"",      qty: 1/50, unit: "case",cost: 48.00 },
  ]},
  { id: "r4", name: "Garlic Knots (dozen)", menuPrice: 7.99, yield: 12, ingredients: [
    { item: "00 Flour",            qty: 0.35, unit: "lb",  cost: 0.68 },
    { item: "Olive oil (gal)",     qty: 0.015, unit: "gal", cost: 32.00 },
    { item: "Garlic/parsley/parm", qty: 1,    unit: "ea",  cost: 0.40 },
    { item: "Paper bag",           qty: 1,    unit: "ea",  cost: 0.08 },
  ]},
  { id: "r5", name: "Chicken Wings (10pc)", menuPrice: 13.99, yield: 1, ingredients: [
    { item: "Chicken wings",       qty: 1.1,  unit: "lb",  cost: 3.85 },
    { item: "Flour dredge",        qty: 0.05, unit: "lb",  cost: 0.68 },
    { item: "Wing sauce",          qty: 0.1,  unit: "qt",  cost: 8.00 },
    { item: "Blue cheese cup",     qty: 1,    unit: "ea",  cost: 0.35 },
    { item: "Container",           qty: 1,    unit: "ea",  cost: 0.24 },
  ]},
  { id: "r6", name: "Caesar Salad", menuPrice: 9.99, yield: 1, ingredients: [
    { item: "Romaine",             qty: 0.4, unit: "lb",  cost: 2.10 },
    { item: "Parmesan",            qty: 0.04, unit: "lb",  cost: 9.20 },
    { item: "Croutons",            qty: 0.05, unit: "lb",  cost: 3.80 },
    { item: "Caesar dressing",     qty: 0.1,  unit: "qt",  cost: 6.50 },
    { item: "Container",           qty: 1,    unit: "ea",  cost: 0.28 },
  ]},
  { id: "r7", name: "Calzone", menuPrice: 12.99, yield: 1, ingredients: [
    { item: "00 Flour",            qty: 0.45, unit: "lb",  cost: 0.68 },
    { item: "Ricotta",             qty: 0.25, unit: "lb",  cost: 3.80 },
    { item: "Mozzarella (block)",  qty: 0.25, unit: "lb",  cost: 3.95 },
    { item: "Pepperoni",           qty: 0.08, unit: "lb",  cost: 6.40 },
    { item: "Container",           qty: 1,    unit: "ea",  cost: 0.40 },
  ]},
];

// -----------------------------------------------------------------------------
// CRM SAMPLE
// -----------------------------------------------------------------------------
const today = new Date();
const daysAgo = (n) => { const d = new Date(today); d.setDate(d.getDate() - n); return d.toISOString().slice(0,10); };
export const SAMPLE_CUSTOMERS = [
  { name: "Maria Gonzalez",   phone: "(407) 555-0142", orders: 34, spent: 648.12, last: daysAgo(3),  tags: ["VIP", "delivery"] },
  { name: "James Carter",     phone: "(407) 555-0198", orders: 28, spent: 512.40, last: daysAgo(8),  tags: ["take-out"] },
  { name: "Rodriguez Family", phone: "(321) 555-0187", orders: 22, spent: 489.50, last: daysAgo(2),  tags: ["VIP", "catering"] },
  { name: "Lisa Park",        phone: "(407) 555-0211", orders: 19, spent: 368.90, last: daysAgo(14), tags: ["dine-in"] },
  { name: "Michael O'Brien",  phone: "(407) 555-0265", orders: 18, spent: 342.20, last: daysAgo(22), tags: ["delivery"] },
  { name: "Sarah Williams",   phone: "(407) 555-0311", orders: 15, spent: 289.75, last: daysAgo(5),  tags: [] },
  { name: "David Chen",       phone: "(321) 555-0344", orders: 12, spent: 245.60, last: daysAgo(35), tags: ["at-risk"] },
  { name: "Jennifer Lopez",   phone: "(407) 555-0388", orders: 11, spent: 228.15, last: daysAgo(4),  tags: ["take-out"] },
  { name: "Robert Smith",     phone: "(407) 555-0412", orders: 9,  spent: 201.30, last: daysAgo(68), tags: ["win-back"] },
  { name: "Angela Brown",     phone: "(321) 555-0456", orders: 8,  spent: 178.40, last: daysAgo(45), tags: ["at-risk"] },
  { name: "Thomas Rivera",    phone: "(407) 555-0489", orders: 7,  spent: 156.90, last: daysAgo(75), tags: ["win-back"] },
  { name: "Patricia Davis",   phone: "(407) 555-0521", orders: 6,  spent: 134.75, last: daysAgo(12), tags: [] },
];

// -----------------------------------------------------------------------------
// RECURRING TASK LIBRARY — FL restaurant operations, safety & compliance
// Frequencies sourced from NFPA 10, NFPA 96, FL Statute 403.0741, FDACS/DBPR
// sev: critical (safety/compliance with legal weight) | important | routine
// -----------------------------------------------------------------------------
export const TASK_LIBRARY = [
  // ---------- DAILY — OPEN ----------
  { id: "d-open-temps", freq: "daily", timeOfDay: "open", category: "Food Safety", sev: "critical",
    title: "Log walk-in & reach-in temps (≤41°F)",
    detail: "Use calibrated thermometer. Record in temp log. Required for DBPR code 03A.",
    assignRole: "manager", est: 5 },
  { id: "d-open-sani", freq: "daily", timeOfDay: "open", category: "Food Safety", sev: "critical",
    title: "Mix sanitizer buckets (200–400ppm quat or 50–100ppm chlorine)",
    detail: "Test with strips. One bucket per station. Change every 4 hours or when visibly soiled.",
    assignRole: "staff", est: 5 },
  { id: "d-open-handwash", freq: "daily", timeOfDay: "open", category: "Food Safety", sev: "critical",
    title: "Stock handwash stations (soap, paper towels, warm water)",
    detail: "Every sink. Verify water reaches 100°F. DBPR code 31B — commonly cited.",
    assignRole: "staff", est: 5 },
  { id: "d-open-fire-access", freq: "daily", timeOfDay: "open", category: "Fire Safety", sev: "critical",
    title: "Verify fire extinguishers unobstructed & pin intact",
    detail: "Walk each extinguisher. Check pin, seal, pressure gauge in green. No boxes/equipment blocking access.",
    assignRole: "manager", est: 5 },
  { id: "d-open-ansul", freq: "daily", timeOfDay: "open", category: "Fire Safety", sev: "critical",
    title: "Visual check hood suppression system (Ansul) nozzles & pull station",
    detail: "Nozzle caps in place, pull station accessible, no grease buildup on nozzles.",
    assignRole: "manager", est: 3 },
  { id: "d-open-dishmachine", freq: "daily", timeOfDay: "open", category: "Food Safety", sev: "important",
    title: "Test dishmachine sanitizer / final rinse temp",
    detail: "Chlorine ≥50ppm OR final rinse ≥160°F utensil surface. Record on log. DBPR code 16.",
    assignRole: "staff", est: 5 },
  { id: "d-open-pest", freq: "daily", timeOfDay: "open", category: "Facility", sev: "important",
    title: "Pest walk-through (droppings, gnaw marks, flies)",
    detail: "Check dry storage corners, under equipment, door sweeps. Log any sightings. #1 cause of FL emergency closures.",
    assignRole: "manager", est: 10 },

  // ---------- DAILY — DURING SERVICE ----------
  { id: "d-svc-temp-4hr", freq: "daily", timeOfDay: "service", category: "Food Safety", sev: "critical",
    title: "4-hour prep line & topping rail temp check",
    detail: "Cold rail ≤41°F, hot wells ≥135°F. Log time + temp. Twice per shift minimum.",
    assignRole: "staff", est: 5 },
  { id: "d-svc-sani-rotate", freq: "daily", timeOfDay: "service", category: "Food Safety", sev: "important",
    title: "Rotate sanitizer buckets & wiping cloths",
    detail: "Every 4 hours. Test strips required. Store cloths IN solution between uses.",
    assignRole: "staff", est: 5 },

  // ---------- DAILY — CLOSE ----------
  { id: "d-close-hood-filters", freq: "daily", timeOfDay: "close", category: "Fire Safety", sev: "critical",
    title: "Pull & soak hood grease filters overnight",
    detail: "NFPA 96 requires filters cleaned at end of each workday. Soak in degreaser; rinse before AM.",
    assignRole: "staff", est: 15 },
  { id: "d-close-floordrains", freq: "daily", timeOfDay: "close", category: "Facility", sev: "important",
    title: "Clean kitchen floor drains (remove grates, clear debris, flush)",
    detail: "Remove grates, clear food debris, flush with hot water, replace. Prevents grease-trap overflow.",
    assignRole: "staff", est: 10 },
  { id: "d-close-prep-surfaces", freq: "daily", timeOfDay: "close", category: "Food Safety", sev: "critical",
    title: "Deep-clean & sanitize all food-contact surfaces",
    detail: "Prep tables, slicers, pizza peels, cutting boards. #2 most-cited DBPR violation (code 22).",
    assignRole: "staff", est: 30 },
  { id: "d-close-trash", freq: "daily", timeOfDay: "close", category: "Facility", sev: "routine",
    title: "Empty trash, take to dumpster, close lid tight",
    detail: "Open dumpster lids attract pests. Verify lid seals. Area swept.",
    assignRole: "staff", est: 10 },
  { id: "d-close-date-rotate", freq: "daily", timeOfDay: "close", category: "Food Safety", sev: "important",
    title: "Date-mark & rotate prep (FIFO)",
    detail: "Label every prepped item with date/discard date. 7-day rule for TCS foods. DBPR code 02C.",
    assignRole: "staff", est: 10 },
  { id: "d-close-cashdrop", freq: "daily", timeOfDay: "close", category: "Operations", sev: "important",
    title: "Close-out register, drop deposit, reconcile shift",
    detail: "Print Z-tape, count drawer, compare to POS report. Log variance.",
    assignRole: "manager", est: 15 },

  // ---------- WEEKLY ----------
  { id: "w-fire-monthly-log", freq: "weekly", category: "Fire Safety", sev: "critical",
    title: "Inspect each fire extinguisher (gauge, pin, seal, tag)",
    detail: "NFPA 10 requires documented monthly visual checks minimum — weekly is safer. Log date + initials on tag.",
    assignRole: "manager", est: 10 },
  { id: "w-grease-trap", freq: "weekly", category: "Facility", sev: "critical",
    title: "Inspect grease trap — measure FOG depth, skim if needed",
    detail: "FL Orange County requires inspection every 7 days. Pump when FOG+solids reach 25% of depth.",
    assignRole: "manager", est: 15 },
  { id: "w-walkin-deep", freq: "weekly", category: "Food Safety", sev: "important",
    title: "Deep-clean walk-in cooler (shelves, floor, gaskets)",
    detail: "Pull everything out. Sanitize shelves, mop floor, inspect gaskets for tears. Check temp drift.",
    assignRole: "staff", est: 45 },
  { id: "w-drain-enzyme", freq: "weekly", category: "Facility", sev: "routine",
    title: "Enzyme treatment in floor drains & grease lines",
    detail: "Breaks down grease between grease trap & floor drain. Pour at close on slowest night.",
    assignRole: "staff", est: 5 },
  { id: "w-inventory", freq: "weekly", category: "Operations", sev: "important",
    title: "Physical inventory count — match to POS usage",
    detail: "Count walk-in, dry storage, freezer. Calc theoretical vs actual. Flag shrinkage >3%.",
    assignRole: "manager", est: 60 },
  { id: "w-dumpster", freq: "weekly", category: "Facility", sev: "routine",
    title: "Pressure-wash dumpster pad & surrounding area",
    detail: "Prevents pest harborage. Required if odor/stains visible on inspection.",
    assignRole: "staff", est: 20 },
  { id: "w-staff-training", freq: "weekly", category: "People", sev: "routine",
    title: "Weekly 10-min staff huddle — one food safety topic",
    detail: "Rotate: handwashing, date marking, allergens, cross-contam, temp logs. Document attendance.",
    assignRole: "manager", est: 15 },
  { id: "w-linens", freq: "weekly", category: "Operations", sev: "routine",
    title: "Swap linens / aprons / bar mops with service",
    detail: "Cintas/Alsco pickup day. Count dirty bag, verify clean count matches.",
    assignRole: "manager", est: 10 },

  // ---------- MONTHLY ----------
  { id: "m-fire-inspect", freq: "monthly", category: "Fire Safety", sev: "critical",
    title: "Monthly fire extinguisher inspection — sign the tag",
    detail: "OSHA 29 CFR 1910.157(e)(2) requires documented monthly visual inspection. Manager initials + date on each tag.",
    assignRole: "manager", est: 15 },
  { id: "m-hood-clean", freq: "monthly", category: "Fire Safety", sev: "critical",
    title: "Professional hood & duct cleaning (high-volume kitchens)",
    detail: "NFPA 96: monthly for solid-fuel/high-volume. Certificate from licensed contractor required. Post in kitchen.",
    assignRole: "manager", est: 0, vendor: true },
  { id: "m-grease-trap-pump", freq: "monthly", category: "Facility", sev: "critical",
    title: "Grease trap pump-out (licensed hauler)",
    detail: "FL Statute 403.0741 requires licensed grease waste hauler. Keep manifest for 3 years. Typical: every 30–90 days.",
    assignRole: "manager", est: 0, vendor: true },
  { id: "m-pest-service", freq: "monthly", category: "Facility", sev: "critical",
    title: "Monthly pest control service — review log with tech",
    detail: "Licensed PCO visits monthly. Review findings, sign log. Keep 12 months onsite. #1 closure reason in FL.",
    assignRole: "manager", est: 30, vendor: true },
  { id: "m-cert-audit", freq: "monthly", category: "Compliance", sev: "important",
    title: "Audit staff food-handler cards & ServSafe cert expirations",
    detail: "Food handler cards renew every 3 years in FL. At least one ServSafe Manager on duty all operating hours.",
    assignRole: "manager", est: 20 },
  { id: "m-menu-cost", freq: "monthly", category: "Operations", sev: "important",
    title: "Recost top 10 menu items — check margin drift",
    detail: "Supplier prices change. Recalc food cost % per item. Flag any item >30% food cost.",
    assignRole: "manager", est: 45 },
  { id: "m-deep-equipment", freq: "monthly", category: "Facility", sev: "important",
    title: "Deep-clean oven, mixer, dough sheeter — behind & under",
    detail: "Pull equipment, clean floor & walls behind. Grease buildup behind ovens is fire hazard & pest attractor.",
    assignRole: "staff", est: 90 },
  { id: "m-po-review", freq: "monthly", category: "Operations", sev: "routine",
    title: "P&L review with bookkeeper — prime cost target",
    detail: "Review prior month P&L. Prime cost target ≤60%. Flag anomalies, plan corrective action.",
    assignRole: "manager", est: 60 },

  // ---------- QUARTERLY ----------
  { id: "q-ansul-inspect", freq: "quarterly", category: "Fire Safety", sev: "critical",
    title: "Semi-annual hood suppression (Ansul) — schedule if due",
    detail: "FL fire code requires semi-annual inspection by licensed contractor. Tag updated. Calendar reminder at 5 months.",
    assignRole: "manager", est: 0, vendor: true },
  { id: "q-backflow", freq: "quarterly", category: "Facility", sev: "important",
    title: "Test backflow preventer (annual; calendar quarterly reminder)",
    detail: "Required annually by most FL water utilities. Licensed tester. Submit report to utility.",
    assignRole: "manager", est: 0, vendor: true },
  { id: "q-license-check", freq: "quarterly", category: "Compliance", sev: "critical",
    title: "Verify all licenses current (DBPR, DOR, local BTR, alcohol if any)",
    detail: "Screenshot each renewal date into calendar. DBPR license renewal window is 90 days.",
    assignRole: "manager", est: 30 },
  { id: "q-mock-inspection", freq: "quarterly", category: "Compliance", sev: "important",
    title: "Run full mock DBPR inspection — score & remediate",
    detail: "Walk the 37-point checklist. Fix every deficiency within 10 days. Document for record.",
    assignRole: "manager", est: 90 },

  // ---------- ANNUAL ----------
  { id: "y-fire-ext-service", freq: "annual", category: "Fire Safety", sev: "critical",
    title: "Annual fire extinguisher professional service (licensed contractor)",
    detail: "FL law requires. New tag with date + contractor license #. Schedule 60 days before expiration.",
    assignRole: "manager", est: 0, vendor: true },
  { id: "y-insurance", freq: "annual", category: "Compliance", sev: "important",
    title: "Renew GL + property + workers' comp insurance",
    detail: "Shop rates 60 days before renewal. Verify coverage: $1M GL minimum, full replacement property.",
    assignRole: "manager", est: 120 },
  { id: "y-dbpr-renew", freq: "annual", category: "Compliance", sev: "critical",
    title: "DBPR food service license renewal",
    detail: "Renews every October 1 in FL. 90-day window. Fees vary by seat count. Non-renewal = closure.",
    assignRole: "manager", est: 45 },
];
